set (CPACK_PACKAGE_DESCRIPTION_SUMMARY "Doomsday Engine")
set (CPACK_PACKAGE_VENDOR "Jaakko Keränen (skyjake)")
set (CPACK_PACKAGE_VERSION_MAJOR ${DENG_VERSION_MAJOR})
set (CPACK_PACKAGE_VERSION_MINOR ${DENG_VERSION_MINOR})
if (DENG_BUILD AND NOT DENG_STABLE)
    set (CPACK_PACKAGE_VERSION_PATCH "${DENG_VERSION_PATCH}-build${DENG_BUILD}")
else ()
    set (CPACK_PACKAGE_VERSION_PATCH ${DENG_VERSION_PATCH})
endif ()
set (CPACK_PACKAGE_INSTALL_DIRECTORY "Doomsday ${DENG_VERSION_MAJOR}.${DENG_VERSION_MINOR}")

set (CPACK_GENERATOR ZIP)

# Source packaging.
set (CPACK_SOURCE_GENERATOR TXZ;ZIP)
set (CPACK_SOURCE_IGNORE_FILES "\\\\.DS_Store$;\\\\.user$;\\\\.user\\\\.")

if (NOT CPack_CMake_INCLUDED)
    include (CPack)
endif ()
