set (CPACK_PACKAGE_VENDOR "dengine.net")
set (CPACK_COMPONENT_SDK_DISABLED TRUE)

set (CPACK_WIX_UPGRADE_GUID "9d4ede0d-dfa4-4695-9710-6d351f35a719")
set (CPACK_WIX_PROPERTY_ARPURLINFOABOUT "http://dengine.net/")
set (CPACK_WIX_PROPERTY_ARPHELPLINK "http://dengine.net/support")
