if (NOT WIN32)
    find_package (ZLIB REQUIRED)
else ()
    # There is a prebuilt zlib DLL in the external/zlib directory.
    set (zlibDir "${DENG_EXTERNAL_SOURCE_DIR}/zlib")
    set (ZLIB_INCLUDE_DIR "${zlibDir}/include")
    set (ZLIB_LIBRARIES   "${zlibDir}/lib/${DENG_ARCH}/zlibwapi.lib")
    set (ZLIB_FOUND YES)
    deng_install_library ("${zlibDir}/lib/${DENG_ARCH}/zlibwapi.dll")
endif ()
