#!/bin/sh

set -e

case "$1" in
  remove|purge|abort-install)
	rm -f /usr/share/games/doom/iwad/tnt/tnt.wad
	rm -f /usr/share/games/doom/iwad/tnt/tnt.gwa
	rm -f /usr/share/games/doom/iwad/tnt/tnt31.gwa
	;;
esac

#DEBHELPER#
