DENG_VERSION            = 1.9.7

JDOOM_VERSION           = 2.0.0
JHERETIC_VERSION        = 2.0.0
JHEXEN_VERSION          = 2.0.0

DEHREAD_VERSION         = 1.2.6
WADMAPCONVERTER_VERSION = 1.0.5
DIRECTSOUND_VERSION     = 1.2.5
OPENAL_VERSION          = 1.2.4
WINMM_VERSION           = 1.0.5

JDOOM64_VERSION         = 0.8.1
