/**\file
 *\section License
 * License: GPL
 * Online License Link: http://www.gnu.org/licenses/gpl.html
 *
 *\author Copyright © 2003-2008 Jaakko Keränen <jaakko.keranen@iki.fi>
 *\author Copyright © 2006-2008 Daniel Swanson <danij@dengine.net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA  02110-1301  USA
 */

/**
 * sounds.h:
 */

#ifndef __JHERETIC_SOUNDS_H__
#define __JHERETIC_SOUNDS_H__

#ifndef __JHERETIC__
#  error "Using jHeretic headers without __JHERETIC__"
#endif

// Sounds.
typedef enum {
    SFX_NONE,
    SFX_GLDHIT,
    SFX_GNTFUL,
    SFX_GNTHIT,
    SFX_GNTPOW,
    SFX_GNTACT,
    SFX_GNTUSE,
    SFX_PHOSHT,
    SFX_PHOHIT,
    SFX_PHOPOW,
    SFX_LOBSHT,
    SFX_LOBHIT,
    SFX_LOBPOW,
    SFX_HRNSHT,
    SFX_HRNHIT,
    SFX_HRNPOW,
    SFX_RAMPHIT,
    SFX_RAMRAIN,
    SFX_BOWSHT,
    SFX_STFHIT,
    SFX_STFPOW,
    SFX_STFCRK,
    SFX_IMPSIT,
    SFX_IMPAT1,
    SFX_IMPAT2,
    SFX_IMPDTH,
    SFX_IMPACT,
    SFX_IMPPAI,
    SFX_MUMSIT,
    SFX_MUMAT1,
    SFX_MUMAT2,
    SFX_MUMDTH,
    SFX_MUMACT,
    SFX_MUMPAI,
    SFX_MUMHED,
    SFX_BSTSIT,
    SFX_BSTATK,
    SFX_BSTDTH,
    SFX_BSTACT,
    SFX_BSTPAI,
    SFX_CLKSIT,
    SFX_CLKATK,
    SFX_CLKDTH,
    SFX_CLKACT,
    SFX_CLKPAI,
    SFX_SNKSIT,
    SFX_SNKATK,
    SFX_SNKDTH,
    SFX_SNKACT,
    SFX_SNKPAI,
    SFX_KGTSIT,
    SFX_KGTATK,
    SFX_KGTAT2,
    SFX_KGTDTH,
    SFX_KGTACT,
    SFX_KGTPAI,
    SFX_WIZSIT,
    SFX_WIZATK,
    SFX_WIZDTH,
    SFX_WIZACT,
    SFX_WIZPAI,
    SFX_MINSIT,
    SFX_MINAT1,
    SFX_MINAT2,
    SFX_MINAT3,
    SFX_MINDTH,
    SFX_MINACT,
    SFX_MINPAI,
    SFX_HEDSIT,
    SFX_HEDAT1,
    SFX_HEDAT2,
    SFX_HEDAT3,
    SFX_HEDDTH,
    SFX_HEDACT,
    SFX_HEDPAI,
    SFX_SORZAP,
    SFX_SORRISE,
    SFX_SORSIT,
    SFX_SORATK,
    SFX_SORACT,
    SFX_SORPAI,
    SFX_SORDSPH,
    SFX_SORDEXP,
    SFX_SORDBON,
    SFX_SBTSIT,
    SFX_SBTATK,
    SFX_SBTDTH,
    SFX_SBTACT,
    SFX_SBTPAI,
    SFX_PLROOF,
    SFX_PLRPAI,
    SFX_PLRDTH,
    SFX_GIBDTH,
    SFX_PLRWDTH,
    SFX_PLRCDTH,
    SFX_ITEMUP,
    SFX_WPNUP,
    SFX_TELEPT,
    SFX_DOROPN,
    SFX_DORCLS,
    SFX_DORMOV,
    SFX_ARTIUP,
    SFX_SWITCH,
    SFX_PSTART,
    SFX_PSTOP,
    SFX_STNMOV,
    SFX_CHICPAI,
    SFX_CHICATK,
    SFX_CHICDTH,
    SFX_CHICACT,
    SFX_CHICPK1,
    SFX_CHICPK2,
    SFX_CHICPK3,
    SFX_KEYUP,
    SFX_RIPSLOP,
    SFX_NEWPOD,
    SFX_PODEXP,
    SFX_BOUNCE,
    SFX_VOLSHT,
    SFX_VOLHIT,
    SFX_BURN,
    SFX_SPLASH,
    SFX_GLOOP,
    SFX_RESPAWN,
    SFX_BLSSHT,
    SFX_BLSHIT,
    SFX_CHAT,
    SFX_ARTIUSE,
    SFX_GFRAG,
    SFX_WATERFL,
    SFX_WIND,
    SFX_AMB1,
    SFX_AMB2,
    SFX_AMB3,
    SFX_AMB4,
    SFX_AMB5,
    SFX_AMB6,
    SFX_AMB7,
    SFX_AMB8,
    SFX_AMB9,
    SFX_AMB10,
    SFX_AMB11,
    NUMSFX
} sfxenum_t;

// Music.
typedef enum {
    MUS_E1M1,
    MUS_E1M2,
    MUS_E1M3,
    MUS_E1M4,
    MUS_E1M5,
    MUS_E1M6,
    MUS_E1M7,
    MUS_E1M8,
    MUS_E1M9,
    MUS_E2M1,
    MUS_E2M2,
    MUS_E2M3,
    MUS_E2M4,
    MUS_E2M5,
    MUS_E2M6,
    MUS_E2M7,
    MUS_E2M8,
    MUS_E2M9,
    MUS_E3M1,
    MUS_E3M2,
    MUS_E3M3,
    MUS_E3M4,
    MUS_E3M5,
    MUS_E3M6,
    MUS_E3M7,
    MUS_E3M8,
    MUS_E3M9,
    MUS_E4M1,
    MUS_E4M2,
    MUS_E4M3,
    MUS_E4M4,
    MUS_E4M5,
    MUS_E4M6,
    MUS_E4M7,
    MUS_E4M8,
    MUS_E4M9,
    MUS_E5M1,
    MUS_E5M2,
    MUS_E5M3,
    MUS_E5M4,
    MUS_E5M5,
    MUS_E5M6,
    MUS_E5M7,
    MUS_E5M8,
    MUS_E5M9,
    MUS_E6M1,
    MUS_E6M2,
    MUS_E6M3,
    MUS_TITL,
    MUS_INTR,
    MUS_CPTD,
    NUMMUSIC
} musicenum_t;

#endif
