/** @file guiapp_macx.mm  macOS-specific GUI app initialization.
 *
 * @authors Copyright (c) 2025 Jaakko Keränen <jaakko.keranen@iki.fi>
 *
 * @par License
 * LGPL: http://www.gnu.org/licenses/lgpl.html
 *
 * <small>This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or (at your
 * option) any later version. This program is distributed in the hope that it
 * will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
 * General Public License for more details. You should have received a copy of
 * the GNU Lesser General Public License along with this program; if not, see:
 * http://www.gnu.org/licenses</small>
 */

#import <AppKit/AppKit.h>
#include <atomic>

static std::atomic<bool> s_mouseTrapped{false};

extern "C" void GuiApp_DiscardWheelMomentum(bool trapped)
{
    s_mouseTrapped = trapped;
}

extern "C" void GuiApp_InitMacOSScrolling()
{
    // Enable momentum (inertia) scrolling. SDL apps must opt in explicitly.
    [[NSUserDefaults standardUserDefaults] setBool:YES
                                            forKey:@"AppleMomentumScrollSupported"];

    // Intercept scroll wheel events before SDL sees them. Momentum-phase events
    // (generated by macOS after the user lifts fingers) are discarded while the
    // mouse is trapped, preventing accidental UI scrolling during gameplay.
    [NSEvent addLocalMonitorForEventsMatchingMask:NSEventMaskScrollWheel
                                          handler:^NSEvent *(NSEvent *event) {
        if (s_mouseTrapped && event.momentumPhase != NSEventPhaseNone)
        {
            return nil; // Discard momentum events when in game input mode.
        }
        return event;
    }];
}
