if (DE_USE_SYSTEM_ASSIMP)
    include (${DE_CMAKE_DIR}/assimp-system.cmake)
else ()
    find_package (assimp REQUIRED CONFIG HINTS "${DE_DEPENDS_DIR}/products")
endif ()

add_library (assimp INTERFACE)
if (DE_USE_SYSTEM_ASSIMP)
    set (_cxxFlags ${ASSIMP_CXX_FLAGS})
    separate_arguments (_cxxFlags)
    target_compile_options (assimp INTERFACE ${_cxxFlags})
    target_include_directories (assimp INTERFACE ${ASSIMP_INCLUDE_DIRS})
    target_link_libraries (assimp INTERFACE ${ASSIMP_LIBRARIES})
else ()
    target_link_libraries (assimp INTERFACE assimp::assimp)
endif ()
