# This ensures that the old-style PK3 packages are compiled when CMake is run
# on any CMake project. All of these should be converted to Doomsday 2 packages.

if (NOT DE_ENABLE_PK3S OR TARGET doomsday.pk3)
    return ()
endif ()

set (outDir "${CMAKE_CURRENT_BINARY_DIR}")

execute_process (COMMAND ${PYTHON_EXECUTABLE}
    "${DE_SOURCE_DIR}/scripts/packres.py"
    "${outDir}"
    WORKING_DIRECTORY "${DE_SOURCE_DIR}"
    OUTPUT_VARIABLE msg
    ERROR_VARIABLE  pk3_err
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
if (pk3_err)
    message (WARNING "packres.py: ${pk3_err}")
endif ()
message (STATUS "Compiling legacy PK3s...")

macro (deng_add_pk3 target)
    add_custom_target (${target})
    set_target_properties (${target} PROPERTIES
        DE_LOCATION ${outDir}/${target}
        FOLDER Packages
    )
    if (APPLE)
        # On macOS, PK3s go into the client app bundle's Resources directory.
        # deng_find_resources() can't pick them up at configure time (they're
        # generated by execute_process above, but apps/client is processed later
        # in the same configure run before the files exist from its perspective).
        install (FILES ${outDir}/${target}
            DESTINATION Doomsday.app/Contents/Resources
            COMPONENT client
        )
    else ()
        install (FILES ${outDir}/${target} DESTINATION ${DE_INSTALL_DATA_DIR})
    endif ()
    if (MSVC)
        # In addition to installing, copy the packages to the build products
        # directories so that executables can be run in them.
        foreach (cfg ${DE_CONFIGURATION_TYPES})
            file (MAKE_DIRECTORY ${DE_VS_STAGING_DIR}/${cfg}/data)
            file (COPY ${outDir}/${outName} DESTINATION ${DE_VS_STAGING_DIR}/${cfg}/data)
        endforeach (cfg)
    endif ()
endmacro (deng_add_pk3)

deng_add_pk3 (doomsday.pk3)
deng_add_pk3 (libdoom.pk3)
deng_add_pk3 (libheretic.pk3)
deng_add_pk3 (libhexen.pk3)
deng_add_pk3 (libdoom64.pk3)
